repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3298ddab3c13dd77d6ce1fc0baf97691430d84b0  # frozen: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-added-large-files
      - id: check-executables-have-shebangs
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 9ff55b0adf11b603e0e2b4e1d639255278f4316f  # frozen: 0.18.3
    hooks:
      - id: check-github-actions
        files: .*/action.ya?ml
      - id: check-github-workflows
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: 5341f388c2a962d3bc66e075f00b80ab45b15f24 # v0.1.20
    hooks:
      - id: shellcheck
