name: "SonarSource LT/SQ release"
description: "Release SonarSource LT & SQ projects"
author: "Thomas Vérin & Malena Ebert"
inputs:
  attach_artifacts_to_github_release:
    description: "Flag to enable attachment of artifacts to the github release"
    default: 'false'
    required: false
  publish_to_binaries:
    description: "Flag to disable the publication to binaries"
    default: 'true'
    required: false
  distribute:
    description: "Flag to enable distribute_release gcp function"
    default: 'false'
    required: false
  distribute_target:
    description: "Switch default distribution target for BinTray"
    required: false
  run_rules_cov:
    description: "Flag to enable running the rules-cov program for languages plugin"
    default: 'false'
    required: false
  test:
    description: "Flag to enable tests"
    default: 'false'
    required: false
outputs:
  releasability:
    description: "Output to detect if releasability was successful"
  promote:
    description: "Output to detect if promote was executed"
  publish_to_binaries:
    description: "Output to detect if publish_to_binaries was executed"
  run_rules_cov:
    description: "Output to detect if run_rules_cov was executed"
  distribute_to_bintray:
    description: "Output to detect if distribute_to_bintray was executed"
  sync_to_central:
    description: "Output to detect if sync_to_central was executed"
runs:
  using: "docker"
  image: "Dockerfile"
