---
name: 'Download build'
description: 'Download all artifacts and checksums of a build'
inputs:
  dryRun:
    description: Flag to enable the dry-run execution
    default: 'false'
    required: false
  local-repo-dir:
    description: 'Empty directory to store the artifacts'
    required: true
  remote-repo:
    description: 'Repository to download from'
    required: true
    default: 'sonarsource-public-releases'
  build-number:
    description: 'Build number'
    required: true
  project-name:
    description: 'Project name for build info (defaults to repository name)'
    required: false
    default: ''
  filter:
    description: 'Path to the artifacts to download'
    required: false
    default: ''
  exclusions:
    description: 'Exclude pattern from downloaded files'
    required: false
    default: '-'
  flat-download:
    description: 'Set to true if you do not wish to have the Artifactory repository path structure created locally for your downloaded files'
    required: false
    default: 'false'
  download-checksums:
    description: 'Set to false if you want to skip downloading the checksums'
    required: false
    default: 'true'
outputs:
  jfrog_dl_options:
    description: Indicate which extra command is passed to jfrog for download
    value: ${{ steps.define-download-options.outputs.jfrog_dl_options }}
runs:
  using: 'composite'
  steps:
    - name: Define download options
      id: define-download-options
      shell: bash
      env:
        EXCLUSIONS: ${{ inputs.exclusions }}
        DRY_RUN: ${{ inputs.dryRun }}
        FLAT_DOWNLOAD: ${{ inputs.flat-download }}
      run: |
        ARGS="--exclusions ${EXCLUSIONS}"

        if [ "${DRY_RUN}" = 'true' ]; then
            ARGS="$ARGS --dry-run=true"
        fi

        if [ "${FLAT_DOWNLOAD}" = 'true' ]; then
            ARGS="$ARGS --flat"
        fi

        # Sanitize output to prevent environment variable injection
        SANITIZED_ARGS=$(echo "${ARGS}" | tr -d '\r\n')
        echo "jfrog_dl_options=${SANITIZED_ARGS}" >> "$GITHUB_OUTPUT"
    - name: Print download options
      env:
        DL_OPTIONS: ${{ steps.define-download-options.outputs.jfrog_dl_options }}
      run: |
        echo "JFrog download options: ${DL_OPTIONS}"
      shell: bash
    - name: Download artifacts
      if: ${{ inputs.dryRun != 'true' }}
      shell: bash
      working-directory: ${{ inputs.local-repo-dir }}
      env:
        PROJECT_NAME: ${{ inputs.project-name }}
        REPO_NAME: ${{ github.event.repository.name }}
        BUILD_NUMBER: ${{ inputs.build-number }}
        JFROG_DL_EXCLUSIONS: ${{ inputs.exclusions }}
        JFROG_DL_REMOTE_REPO: ${{ inputs.remote-repo }}
        FILTER: ${{ inputs.filter }}
        JFROG_DL_OPTIONS: ${{ steps.define-download-options.outputs.jfrog_dl_options }}
      run: |
        # Safely construct build name
        if [ -n "${PROJECT_NAME}" ]; then
          JFROG_DL_BUILD="${PROJECT_NAME}/${BUILD_NUMBER}"
        else
          JFROG_DL_BUILD="${REPO_NAME}/${BUILD_NUMBER}"
        fi

        REMOTE_REPO="${JFROG_DL_REMOTE_REPO}"
        if [ -n "${FILTER}" ]; then
          REMOTE_REPO="${REMOTE_REPO}/${FILTER}/"
        fi
        echo "${REMOTE_REPO}"
        jfrog rt download \
          --fail-no-op ${JFROG_DL_OPTIONS} \
          --build "${JFROG_DL_BUILD}" \
          "${REMOTE_REPO}"
    - name: Download checksums
      if: ${{ inputs.dryRun != 'true' && inputs.download-checksums == 'true' }}
      shell: bash
      working-directory: ${{ inputs.local-repo-dir }}
      env:
        JFROG_DL_REMOTE_REPO: ${{ inputs.remote-repo }}
      run: >
        find . -type f
        -not \( -name "*.asc" -or -name "*.md5" -or -name "*.sha1" -or -name "*.sha256" \)
        -exec jfrog rt curl "${JFROG_DL_REMOTE_REPO}/{{}}.{md5,sha1,sha256}" --output "#1.#2" \;
