name: "Maven Central Sync"
description: "Syncs a open source project with maven central"
inputs:
  local-repo-dir:
    description: "Directory of artifacts to sync"
    required: true
  central-url:
    description: "URL to the Central Portal instance"
    required: false
    default: "https://central.sonatype.com"
  auto-publish:
    description: "If true, automatically publish after upload and validation"
    required: false
    default: "true"
outputs:
  deployment-id:
    description: "ID of the deployment"
    value: ${{ steps.upload.outputs.deployment-id }}
runs:
  using: "composite"
  steps:
    - name: Upload to Central Portal
      id: upload
      shell: bash
      run: ${{ github.action_path }}/maven-central-publish.sh "${{ inputs.local-repo-dir }}" "${{ inputs.central-url }}" "${{ inputs.auto-publish }}"
