name: "Maven Central Sync"
description: "Syncs a open source project with maven central"
inputs:
  local-repo-dir:
    description: "Directory of artifacts to sync"
    required: true
  nexus-url:
    description: "URL to the nexus instance"
    required: true
    default: "https://s01.oss.sonatype.org/"
  staging-profile-id:
    description: "Staging profile id of Nexus"
    required: true
    default: "13c1877339a4cf"
  do-release:
    description: "If false skip release, only close the staging repo"
    required: true
    default: "true"
outputs:
  repo:
    description: "Name of the staging repo"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.local-repo-dir }}
    - ${{ inputs.nexus-url }}
    - ${{ inputs.staging-profile-id }}
    - ${{ inputs.do-release }}
