name: 'Helm chart update index'
description: 'Release a helm chart on github'
inputs:
  package-path:
    description: 'Path to the package'
    required: true
  release-name:
    description: 'Name of the github release'
    required: true
    default: "{{ .Version }}"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "${{ inputs.package-path }}"
    - "${{ inputs.release-name }}"