on:
  pull_request:
    types: [opened, reopened, labeled, edited]
    branches:
      - 'releases/**'

permissions:
  contents: read
  pull-requests: write

jobs:
  autoapproval:
    runs-on: ubuntu-latest
    name: Autoapproval
    steps:
      - uses: dkhmelenko/autoapproval@76e6fa8313951249b9477a855f0d09ad6510b696 # v1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
