on:
  pull_request:
  push:
    branches:
      - master

jobs:
  it-tests-default-values:
    name: IT Test - use default inputs values should generate expected output"
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup JFrog
        uses: SonarSource/jfrog-setup-wrapper@b243f5b25440cdcb062db329eec5fd9c9cd2dab2 # 3.7.0
        with:
          artifactoryRoleSuffix: "private-reader"
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0 (Necessary to access local action)
      - uses: ./download-build/
        name: Given download-build is used with default values and dryRun enabled
        id: test-data
        with:
          dryRun: true
          build-number: '5432'
          local-repo-dir: '.'
          # use default values for the following:
          #flat-download:
          #exclusions:
      - uses: nick-fields/assert-action@9d4e34b06ce426ffbec11d91e220b8a90fd36bdb # v3.0.1
        name: Then outputs.jfrog_dl_options value must contains --flat, --exclusions and --dry-run
        with:
          expected: '--exclusions - --dry-run=true'
          actual: ${{ steps.test-data.outputs.jfrog_dl_options }}
          comparison: exact

  it-tests-use-flat-download-true:
    name: IT Test - use flat-download=true should generate expected output"
    runs-on: github-ubuntu-latest-s
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Setup JFrog
        uses: SonarSource/jfrog-setup-wrapper@b243f5b25440cdcb062db329eec5fd9c9cd2dab2 # 3.7.0
        with:
          artifactoryRoleSuffix: "private-reader"
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0 (Necessary to access local action)
      - uses: ./download-build/
        name: Given download-build is used with flat-download=true, exclusions and dryRun enabled
        id: test-data
        with:
          dryRun: true
          build-number: '5432'
          flat-download: 'true'
          exclusions: '-'
          local-repo-dir: '.'
      - uses: nick-fields/assert-action@9d4e34b06ce426ffbec11d91e220b8a90fd36bdb # v3.0.1
        name: Then outputs.jfrog_dl_options value must contains --flat, --exclusions and --dry-run
        with:
          expected: '--exclusions - --dry-run=true --flat'
          actual: ${{ steps.test-data.outputs.jfrog_dl_options }}
          comparison: exact

  it-tests:
      name: "All IT Tests have to pass (download-build)"
      runs-on: github-ubuntu-latest-s
      if: always()
      needs:
        # Add your tests here so that they prevent the merge of broken changes
        - it-tests-default-values
        - it-tests-use-flat-download-true
      steps:
        - uses: re-actors/alls-green@b5b5b37504aa4183270bd3d855c52a67f212be35 # v1.3.0
          with:
            jobs: ${{ toJSON(needs) }}
