# yamllint disable rule:line-length
---
name: Release reusable workflow

on:
  workflow_call:
    inputs:
      dryRun:
        type: boolean
        description: Flag to enable the dry-run execution
        default: false
        required: false
      publishToBinaries:
        type: boolean
        description: Flag to enable the publication to binaries
        default: false
        required: false
      publishJavadoc:
        type: boolean
        description: Flag to enable the javadoc publication
        default: false
        required: false
      javadocDestinationDirectory:
        type: string
        description: Name of the directory to use at https://javadocs.sonarsource.org/ when publishJavadoc is set to true
        required: false
      binariesS3Bucket:
        type: string
        description: Target bucket
        default: downloads-cdn-eu-central-1-prod
        required: false
      slackChannel:
        type: string
        description: Channel to post notifications
        default: build
        required: false
      vaultAddr:
        type: string
        description: Custom vault installation
        default: https://vault.sonar.build:8200
        required: false
      artifactoryRoleSuffix:
        type: string
        description: Artifactory promoter suffix specified in Vault repo config
        default: promoter
        required: false
      mavenCentralSync:
        type: boolean
        description: Enable synchronization to Maven Central
        default: false
        required: false
      mavenCentralSyncExclusions:
        type: string
        description: exclusions for the JFrog build download
        default: "-"
        required: false
      publishToPyPI:
        type: boolean
        description: Publish Python artifacts to https://pypi.org
        default: false
        required: false
      publishToTestPyPI:
        type: boolean
        description: Publish Python artifacts to https://test.pypi.org
        default: false
        required: false
      # Releasability checks are not fully implemented for Python projects
      # This flag allows to skip releasability checks and allow releasing the artifacts. It is ignored for non-python projects
      skipPythonReleasabilityChecks:
        type: boolean
        description: Skip releasability checks for Python projects
        default: false
        required: false

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # to authenticate via OIDC
      contents: write  # to revert a github release
    timeout-minutes: 30
    if: ${{ inputs.dryRun == true || github.event_name == 'release' && github.event.action == 'published' }}
    outputs:
      releasability: ${{ steps.release.outputs.releasability }}
      promote: ${{ steps.release.outputs.promote }}
      publish_to_binaries: ${{ steps.release.outputs.publish_to_binaries }}
      release: ${{ steps.release.outputs.release }}
    steps:
      # Clone gh-action_release repository to run actions locally
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # Hardcode the repository name, because GitHub Actions does not provide a built-in context or variable
          # to directly reference the repository where the reusable workflow is defined
          repository: SonarSource/gh-action_release
          # This property is changed during the release process to reference the correct tag
          # During development change this to your branch name to run it in another repository
          ref: ${{ github.ref }}
          path: gh-action_release
      # Clone the calling repo for checking releasability prerequisites
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          path: ${{ github.event.repository.name }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: eu-central-1
          role-to-assume: "arn:aws:iam::064493320159:role/ReleasbilityChecksCICDRole"
      - name: Vault Secrets
        id: secrets
        if: ${{ inputs.dryRun != true }}
        uses: SonarSource/vault-action-wrapper@d0877ce7085bc313bd7a7b99c4e4489d42fb40e1 # tag=3.0.0
        with:
          url: ${{ inputs.vaultAddr }}
          secrets: |
            development/artifactory/token/{REPO_OWNER_NAME_DASH}-${{ inputs.artifactoryRoleSuffix }} access_token | artifactory_access_token;
            development/kv/data/slack token | slack_api_token;
            development/kv/data/repox url | artifactory_url;
      - name: Vault Binaries AWS Secrets
        id: secrets-binaries-aws
        if: ${{ inputs.dryRun != true && inputs.publishToBinaries }}
        uses: SonarSource/vault-action-wrapper@d0877ce7085bc313bd7a7b99c4e4489d42fb40e1 # tag=3.0.0
        with:
          url: ${{ inputs.vaultAddr }}
          secrets: |
            development/aws/sts/downloads access_key | binaries_aws_access_key_id;
            development/aws/sts/downloads secret_key | binaries_aws_secret_access_key;
            development/aws/sts/downloads security_token | binaries_aws_security_token;
      - name: Parse Vault Output
        id: parse_vault
        env:
          DUMMY_VALUES: ${{ inputs.dryRun }}
          SECRET_OUTPUTS: ${{ toJson(steps.secrets.outputs) }}
          SECRET_AWS_OUTPUTS: ${{ toJson(steps.secrets-binaries-aws.outputs) }}
        run: |
          if [[ "${DUMMY_VALUES}" == "true" ]]; then
            {
              echo "artifactory_access_token=test"
              echo "slack_api_token=test"
              echo "binaries_aws_access_key_id=test"
              echo "binaries_aws_secret_access_key=test"
              echo "binaries_aws_security_token=test"
            } >> "${GITHUB_OUTPUT}"
            exit 0
          fi
          echo "${SECRET_OUTPUTS}" | jq -r '.vault | fromjson | to_entries[] | (.key + "<<EOF\n" + .value + "\nEOF")' >> "${GITHUB_OUTPUT}"
          if [[ "${SECRET_AWS_OUTPUTS}" != "{}" ]]; then
            echo "${SECRET_AWS_OUTPUTS}" | jq -r '.vault | fromjson | to_entries[] | (.key + "<<EOF\n" + .value + "\nEOF")' >> "${GITHUB_OUTPUT}"
          fi

      - name: Releasability check prerequisites
        id: releasability_prerequisites
        env:
          SKIP_PYTHON_RELEASABILITY_CHECKS: ${{ inputs.skipPythonReleasabilityChecks }}
        run: |
          # Skip releasability checks if the project contains pyproject.toml file
          if test -f "${{ github.event.repository.name }}/pyproject.toml" && "$SKIP_PYTHON_RELEASABILITY_CHECKS" == "true"  ; then
            echo "skip_releasability_checks=true" >> "${GITHUB_OUTPUT}"
          else
            echo "skip_releasability_checks=false" >> "${GITHUB_OUTPUT}"
          fi

      - uses: SonarSource/gh-action_releasability@v1.0.0
        id: releasability
        if: ${{ steps.releasability_prerequisites.outputs.skip_releasability_checks != 'true' && inputs.dryRun != true }}
        with:
          branch: ${{ github.ref_name }}
          commit-sha: ${{ github.sha }}
          organization: ${{ github.repository_owner }}
          repository: ${{ github.event.repository.name }}
          version: ${{ github.event.release.tag_name }}

      - name: Release ${{ github.event.release.tag_name }}
        id: release
        uses: ./gh-action_release/main
        with:
          publish_to_binaries: ${{ inputs.publishToBinaries }}  # Used only if the binaries are delivered to customers
          slack_channel: ${{ inputs.slackChannel }}
          dry_run: ${{ inputs.dryRun }}
        env:
          PYTHONUNBUFFERED: 1
          ARTIFACTORY_ACCESS_TOKEN: ${{ steps.parse_vault.outputs.artifactory_access_token }}
          BINARIES_AWS_DEPLOY: ${{ inputs.binariesS3Bucket }}  # Required for pushing the binaries
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_API_TOKEN: ${{ steps.parse_vault.outputs.slack_api_token }}
          BINARIES_AWS_ACCESS_KEY_ID: ${{ steps.parse_vault.outputs.binaries_aws_access_key_id }}
          BINARIES_AWS_SECRET_ACCESS_KEY: ${{ steps.parse_vault.outputs.binaries_aws_secret_access_key }}
          BINARIES_AWS_SESSION_TOKEN: ${{ steps.parse_vault.outputs.binaries_aws_security_token }}
          BINARIES_AWS_DEFAULT_REGION: eu-central-1
          SKIP_RELEASABILITY_CHECKS: ${{ steps.releasability_prerequisites.outputs.skip_releasability_checks }}
      - name: Release action results
        if: always()
        run: |
          echo "${{ steps.releasability.outputs.status }}"
          echo "${{ steps.release.outputs.promote }}"
          echo "${{ steps.release.outputs.publish_to_binaries }}"
          echo "${{ steps.release.outputs.release }}"

  mavenCentral:
    name: Maven Central
    needs: release
    if: ${{ inputs.mavenCentralSync && inputs.dryRun != true }}
    uses: ./.github/workflows/maven-central.yaml
    with:
      vaultAddr: ${{ inputs.vaultAddr }}
      artifactoryRoleSuffix: ${{ inputs.artifactoryRoleSuffix }}
      downloadExclusions: ${{ inputs.mavenCentralSyncExclusions }}

  javadocPublication:
    name: Javadoc publication
    needs: release
    if: ${{ inputs.publishJavadoc && inputs.dryRun != true }}
    uses: ./.github/workflows/javadoc-publication.yaml
    with:
      dryRun: ${{ inputs.dryRun }}
      vaultAddr: ${{ inputs.vaultAddr }}
      artifactoryRoleSuffix: ${{ inputs.artifactoryRoleSuffix }}
      javadocDestinationDirectory: ${{ inputs.javadocDestinationDirectory }}

  testPypi:
    name: TestPyPI
    needs: release
    if: ${{ inputs.publishToTestPyPI && inputs.dryRun != true }}
    uses: ./.github/workflows/pypi.yaml
    with:
      vaultAddr: ${{ inputs.vaultAddr }}
      vaultTokenKey: pypi-test
      artifactoryRoleSuffix: ${{ inputs.artifactoryRoleSuffix }}
      pypiRepoUrl: "https://test.pypi.org/legacy/"
      slackChannel: ${{ inputs.slackChannel }}

  pypi:
    name: PyPi
    needs: release
    if: ${{ inputs.publishToPyPI && inputs.dryRun != true }}
    uses: ./.github/workflows/pypi.yaml
    with:
      vaultAddr: ${{ inputs.vaultAddr }}
      artifactoryRoleSuffix: ${{ inputs.artifactoryRoleSuffix }}
      slackChannel: ${{ inputs.slackChannel }}
