---
name: Releasability Check
on:
  workflow_call:
    inputs:
      version:
        description: Version to check releasability on
        required: true
        type: string

jobs:
  releasability_check:
    name: Releasability Check
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # This will be called from other repositories, so we need to ensure we
          # are cloning this one instead of the one of the caller.
          repository: SonarSource/gh-action_release
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: "3.10"
      - name: Releasability Check
        working-directory: main
        run: |
          python -m pip install --upgrade pip pipenv
          make releasability-check
