---
name: Releasability Check
on:
  workflow_call:
    inputs:
      version:
        description: Version to check releasability on
        required: true
        type: string

jobs:
  releasability_check:
    name: Releasability Check
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@d0877ce7085bc313bd7a7b99c4e4489d42fb40e1 # tag=3.0.0
        with:
          secrets: |
            development/kv/data/burgr github_username | burgrx_username;
            development/kv/data/burgr github_password | burgrx_password;
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          # This will be called from other repositories, so we need to ensure we
          # are cloning this one instead of the one of the caller.
          repository: SonarSource/gh-action_release
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.10"
      - name: Releasability Check
        working-directory: main
        run: |
          python -m pip install --upgrade pip pipenv
          make releasability-check
        env:
          BURGRX_USER: ${{ fromJSON(steps.secrets.outputs.vault).burgrx_username }}
          BURGRX_PASSWORD: ${{ fromJSON(steps.secrets.outputs.vault).burgrx_password }}
