---
name: Releasability Check
on:
  workflow_call: {}

jobs:
  releasability_check:
    name: Releasability Check
    runs-on: ubuntu-20.04
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Vault Secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@d1c1ab4ca5ad07fd9cdfe1eff038a39673dfca64  # tag=2.4.2-1
        with:
          secrets: |
            development/kv/data/burgr github_username | burgrx_username;
            development/kv/data/burgr github_password | burgrx_password;
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2
        with:
          # This will be called from other repositories, so we need to ensure we
          # are cloning this one instead of the one of the caller.
          repository: SonarSource/gh-action_release
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@d09bd5e6005b175076f227b13d9730d56e9dcfcb # tag=v4.0.0
        with:
          python-version: "3.10"
      - name: Releasability Check
        working-directory: main
        run: |
          python -m pip install --upgrade pip pipenv
          make releasability-check
        env:
          BURGRX_USER: ${{ fromJSON(steps.secrets.outputs.vault).burgrx_username }}
          BURGRX_PASSWORD: ${{ fromJSON(steps.secrets.outputs.vault).burgrx_password }}
