name: Update v-branch
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release tag
        required: true
        type: string

jobs:
  update-v-branch:
    name: Update v* branch to ${{ inputs.tag }}
    runs-on: github-ubuntu-latest-s
    permissions:
      contents: read
      id-token: write
    steps:
      - name: get secrets
        id: secrets
        uses: SonarSource/vault-action-wrapper@881045d830534a70ec3c7c275fa3714412c8ff6e # 3.6.1
        with:
          secrets: |
              development/github/token/{REPO_OWNER_NAME_DASH}-release token | github_token;
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          token: ${{ fromJSON(steps.secrets.outputs.vault).github_token }}
      - name: Git config
        run: |
          git config user.name sonartech
          git config user.email sonartech@sonarsource.com
      - name: update v* branch
        run: scripts/updatevbranch.sh ${{ inputs.tag }}
